"""Initial schema with all models

Revision ID: 839d4ee251e4
Revises: 
Create Date: 2025-10-30 16:45:37.122598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '839d4ee251e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('malls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geojson_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outfit_hash', sa.String(length=64), nullable=False),
    sa.Column('detection_date', sa.Date(), nullable=False),
    sa.Column('outfit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visitor_profile_outfit_date', 'visitor_profiles', ['outfit_hash', 'detection_date'], unique=False)
    op.create_index(op.f('ix_visitor_profiles_detection_date'), 'visitor_profiles', ['detection_date'], unique=False)
    op.create_index(op.f('ix_visitor_profiles_outfit_hash'), 'visitor_profiles', ['outfit_hash'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mall_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_mall_id'), 'tenants', ['mall_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mall_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_mall_id'), 'stores', ['mall_id'], unique=False)
    op.create_index(op.f('ix_stores_tenant_id'), 'stores', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MALL_OPERATOR', 'TENANT_MANAGER', 'TENANT_VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mall_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mall_id'), 'users', ['mall_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('camera_pins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mall_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lng', sa.Float(), nullable=False),
    sa.Column('pin_type', sa.String(length=20), nullable=False),
    sa.Column('adjacent_to', sa.ARRAY(sa.UUID()), server_default='{}', nullable=True),
    sa.Column('transit_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('camera_fps', sa.Integer(), nullable=False),
    sa.Column('camera_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_pins_mall_id'), 'camera_pins', ['mall_id'], unique=False)
    op.create_index(op.f('ix_camera_pins_store_id'), 'camera_pins', ['store_id'], unique=False)
    op.create_table('journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('mall_id', sa.UUID(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_point', sa.UUID(), nullable=False),
    sa.Column('exit_point', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_point'], ['camera_pins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exit_point'], ['camera_pins.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journey_date_mall', 'journeys', ['journey_date', 'mall_id'], unique=False)
    op.create_index(op.f('ix_journeys_entry_point'), 'journeys', ['entry_point'], unique=False)
    op.create_index(op.f('ix_journeys_exit_point'), 'journeys', ['exit_point'], unique=False)
    op.create_index(op.f('ix_journeys_journey_date'), 'journeys', ['journey_date'], unique=False)
    op.create_index(op.f('ix_journeys_mall_id'), 'journeys', ['mall_id'], unique=False)
    op.create_index(op.f('ix_journeys_visitor_id'), 'journeys', ['visitor_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_pin_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_pin_id'], ['camera_pins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_camera_pin_id'), 'videos', ['camera_pin_id'], unique=False)
    op.create_index(op.f('ix_videos_processing_status'), 'videos', ['processing_status'], unique=False)
    op.create_table('tracklets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mall_id', sa.UUID(), nullable=False),
    sa.Column('pin_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('t_in', sa.DateTime(), nullable=False),
    sa.Column('t_out', sa.DateTime(), nullable=False),
    sa.Column('outfit_vec', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('outfit_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('physique', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('box_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pin_id'], ['camera_pins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracklet_pin_time', 'tracklets', ['pin_id', 't_in', 't_out'], unique=False)
    op.create_index(op.f('ix_tracklets_mall_id'), 'tracklets', ['mall_id'], unique=False)
    op.create_index(op.f('ix_tracklets_pin_id'), 'tracklets', ['pin_id'], unique=False)
    op.create_index(op.f('ix_tracklets_video_id'), 'tracklets', ['video_id'], unique=False)
    op.create_table('associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mall_id', sa.UUID(), nullable=False),
    sa.Column('from_tracklet_id', sa.UUID(), nullable=False),
    sa.Column('to_tracklet_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_tracklet_id'], ['tracklets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mall_id'], ['malls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_tracklet_id'], ['tracklets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_associations_from_tracklet_id'), 'associations', ['from_tracklet_id'], unique=False)
    op.create_index(op.f('ix_associations_mall_id'), 'associations', ['mall_id'], unique=False)
    op.create_index(op.f('ix_associations_to_tracklet_id'), 'associations', ['to_tracklet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_associations_to_tracklet_id'), table_name='associations')
    op.drop_index(op.f('ix_associations_mall_id'), table_name='associations')
    op.drop_index(op.f('ix_associations_from_tracklet_id'), table_name='associations')
    op.drop_table('associations')
    op.drop_index(op.f('ix_tracklets_video_id'), table_name='tracklets')
    op.drop_index(op.f('ix_tracklets_pin_id'), table_name='tracklets')
    op.drop_index(op.f('ix_tracklets_mall_id'), table_name='tracklets')
    op.drop_index('ix_tracklet_pin_time', table_name='tracklets')
    op.drop_table('tracklets')
    op.drop_index(op.f('ix_videos_processing_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_camera_pin_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_journeys_visitor_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_mall_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_journey_date'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_exit_point'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_entry_point'), table_name='journeys')
    op.drop_index('ix_journey_date_mall', table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_camera_pins_store_id'), table_name='camera_pins')
    op.drop_index(op.f('ix_camera_pins_mall_id'), table_name='camera_pins')
    op.drop_table('camera_pins')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_mall_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_tenant_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_mall_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_tenants_mall_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_visitor_profiles_outfit_hash'), table_name='visitor_profiles')
    op.drop_index(op.f('ix_visitor_profiles_detection_date'), table_name='visitor_profiles')
    op.drop_index('ix_visitor_profile_outfit_date', table_name='visitor_profiles')
    op.drop_table('visitor_profiles')
    op.drop_table('malls')
    # ### end Alembic commands ###
